import type { SavingsGoal, SummaryMetric } from "@/types/finance";

export const savingsGoalSummaries: SummaryMetric[] = [
  {
    label: "Total Target",
    value: "MMK 125,000",
    icon: "target",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Total Saved",
    value: "MMK 42,500",
    icon: "savings",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Remaining",
    value: "MMK 82,500",
    icon: "timeline",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Active Goals",
    value: "4",
    icon: "dashboard",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
];

export const savingsGoals: SavingsGoal[] = [
  {
    id: "SVG-1001",
    name: "Emergency Fund",
    targetAmount: "MMK 10,000",
    savedAmount: "MMK 6,500",
    remainingAmount: "MMK 3,500",
    progressPercent: 65,
    targetDate: "Dec 2026",
    monthlyContribution: "MMK 500",
    account: "High-Yield Savings",
    status: "On Track",
    icon: "savings",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "SVG-1002",
    name: "House Downpayment",
    targetAmount: "MMK 100,000",
    savedAmount: "MMK 25,000",
    remainingAmount: "MMK 75,000",
    progressPercent: 25,
    targetDate: "Jun 2028",
    monthlyContribution: "MMK 1,500",
    account: "High-Yield Savings",
    status: "On Track",
    icon: "home",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "SVG-1003",
    name: "New Car",
    targetAmount: "MMK 15,000",
    savedAmount: "MMK 11,000",
    remainingAmount: "MMK 4,000",
    progressPercent: 73,
    targetDate: "Mar 2027",
    monthlyContribution: "MMK 450",
    account: "Main Checking",
    status: "On Track",
    icon: "credit",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
  {
    id: "SVG-1004",
    name: "Travel Reserve",
    targetAmount: "MMK 5,000",
    savedAmount: "MMK 0",
    remainingAmount: "MMK 5,000",
    progressPercent: 0,
    targetDate: "Nov 2026",
    monthlyContribution: "MMK 300",
    account: "Travel Wallet",
    status: "Behind",
    icon: "travel",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
];
