import type { SavingsGoal, SummaryMetric } from "@/types/finance";

export const savingsGoalSummaries: SummaryMetric[] = [
  {
    label: "Total Target",
    value: "$125,000",
    icon: "target",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Total Saved",
    value: "$42,500",
    icon: "savings",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Remaining",
    value: "$82,500",
    icon: "timeline",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Active Goals",
    value: "4",
    icon: "dashboard",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
];

export const savingsGoals: SavingsGoal[] = [
  {
    id: "SVG-1001",
    name: "Emergency Fund",
    targetAmount: "$10,000",
    savedAmount: "$6,500",
    remainingAmount: "$3,500",
    progressPercent: 65,
    targetDate: "Dec 2026",
    monthlyContribution: "$500",
    account: "High-Yield Savings",
    status: "On Track",
    icon: "savings",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "SVG-1002",
    name: "House Downpayment",
    targetAmount: "$100,000",
    savedAmount: "$25,000",
    remainingAmount: "$75,000",
    progressPercent: 25,
    targetDate: "Jun 2028",
    monthlyContribution: "$1,500",
    account: "High-Yield Savings",
    status: "On Track",
    icon: "home",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "SVG-1003",
    name: "New Car",
    targetAmount: "$15,000",
    savedAmount: "$11,000",
    remainingAmount: "$4,000",
    progressPercent: 73,
    targetDate: "Mar 2027",
    monthlyContribution: "$450",
    account: "Main Checking",
    status: "On Track",
    icon: "credit",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
  {
    id: "SVG-1004",
    name: "Travel Reserve",
    targetAmount: "$5,000",
    savedAmount: "$0",
    remainingAmount: "$5,000",
    progressPercent: 0,
    targetDate: "Nov 2026",
    monthlyContribution: "$300",
    account: "Travel Wallet",
    status: "Behind",
    icon: "travel",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
];
