import type { SubscriptionRecord, SummaryMetric, UpcomingSubscriptionBilling } from "@/types/finance";

export const subscriptionSummaries: SummaryMetric[] = [
  {
    label: "Monthly Total Cost",
    value: "$145.00",
    icon: "receipt",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Yearly Total Cost",
    value: "$1,740.00",
    icon: "account",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Active Subscriptions",
    value: "12",
    icon: "subscriptions",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Upcoming 7 Days",
    value: "3",
    icon: "calendar",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
];

export const subscriptions: SubscriptionRecord[] = [
  {
    id: "SUB-1001",
    name: "ChatGPT",
    amount: "$20.00",
    billingCycle: "Monthly",
    paymentAccount: "Main Checking",
    nextBillingDate: "Nov 15, 2026",
    status: "Active",
    category: "Software Tools",
    reminderEnabled: true,
    icon: "subscriptions",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "SUB-1002",
    name: "iCloud",
    amount: "$9.99",
    billingCycle: "Monthly",
    paymentAccount: "Amex Platinum",
    nextBillingDate: "Nov 18, 2026",
    status: "Active",
    category: "Software Tools",
    reminderEnabled: true,
    icon: "document",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
  {
    id: "SUB-1003",
    name: "Netflix",
    amount: "$15.49",
    billingCycle: "Monthly",
    paymentAccount: "Chase Sapphire",
    nextBillingDate: "Nov 25, 2026",
    status: "Paused",
    category: "Entertainment",
    reminderEnabled: false,
    icon: "box",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
  {
    id: "SUB-1004",
    name: "Adobe Creative Cloud",
    amount: "$54.99",
    billingCycle: "Monthly",
    paymentAccount: "Main Checking",
    nextBillingDate: "Nov 21, 2026",
    status: "Expiring",
    category: "Software Tools",
    reminderEnabled: true,
    icon: "document",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
];

export const upcomingSubscriptionBillings: UpcomingSubscriptionBilling[] = [
  {
    id: "BILL-1001",
    dateLabel: "Tomorrow, Nov 15",
    name: "ChatGPT Plus",
    amount: "$20.00",
    billingCycle: "Monthly",
    icon: "subscriptions",
    isNext: true,
  },
  {
    id: "BILL-1002",
    dateLabel: "Nov 18",
    name: "iCloud Storage",
    amount: "$9.99",
    billingCycle: "Monthly",
    icon: "document",
  },
  {
    id: "BILL-1003",
    dateLabel: "Nov 21",
    name: "Adobe CC",
    amount: "$54.99",
    billingCycle: "Monthly",
    icon: "document",
  },
];
