import type { FinancialCategory, SummaryMetric } from "@/types/finance";

export const categorySummaries: SummaryMetric[] = [
  {
    label: "Expense Categories",
    value: "9",
    icon: "trendingDown",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    label: "Income Categories",
    value: "7",
    icon: "trendingUp",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Monthly Tracked",
    value: "$7,240",
    icon: "chart",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Active Categories",
    value: "16",
    icon: "category",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
];

export const categories: FinancialCategory[] = [
  {
    id: "CAT-1001",
    name: "Food",
    type: "Expense",
    description: "Groceries and dining out",
    monthlyAverage: "$850",
    transactionCount: 42,
    icon: "food",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
    marker: "bg-[#4edea3]",
    scopes: ["Transactions", "Budgets", "Subscriptions", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-1002",
    name: "Travel",
    type: "Expense",
    description: "Flights, hotels, and transit",
    monthlyAverage: "$320",
    transactionCount: 8,
    icon: "travel",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
    marker: "bg-[#2170e4]",
    scopes: ["Transactions", "Budgets", "Savings Goals", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-1003",
    name: "Housing",
    type: "Expense",
    description: "Rent, repairs, and maintenance",
    monthlyAverage: "$2,100",
    transactionCount: 1,
    icon: "home",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
    marker: "bg-[#4f46e5]",
    scopes: ["Transactions", "Budgets", "Savings Goals", "Debts", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-1004",
    name: "Shopping",
    type: "Expense",
    description: "Clothing and retail purchases",
    monthlyAverage: "$450",
    transactionCount: 15,
    icon: "shopping",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
    marker: "bg-[#92400e]",
    scopes: ["Transactions", "Budgets", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-1005",
    name: "Utilities",
    type: "Expense",
    description: "Internet, mobile, electricity",
    monthlyAverage: "$185",
    transactionCount: 6,
    icon: "settings",
    tone: "text-[#45464d]",
    bg: "bg-[#f8f9ff]",
    marker: "bg-[#76777d]",
    scopes: ["Transactions", "Budgets", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-1006",
    name: "Subscriptions",
    type: "Expense",
    description: "Software and recurring services",
    monthlyAverage: "$120",
    transactionCount: 9,
    icon: "subscriptions",
    tone: "text-[#7c3aed]",
    bg: "bg-[#f5f3ff]",
    marker: "bg-[#7c3aed]",
    scopes: ["Transactions", "Budgets", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-1007",
    name: "Medical",
    type: "Expense",
    description: "Healthcare and pharmacy",
    monthlyAverage: "$90",
    transactionCount: 3,
    icon: "medical",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
    marker: "bg-[#b42318]",
    scopes: ["Transactions", "Budgets", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-2001",
    name: "Salary",
    type: "Income",
    description: "Primary employment income",
    monthlyAverage: "$8,500",
    transactionCount: 2,
    icon: "trendingUp",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
    marker: "bg-[#047857]",
    scopes: ["Transactions", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-2002",
    name: "Freelance",
    type: "Income",
    description: "Client projects and consulting",
    monthlyAverage: "$1,200",
    transactionCount: 4,
    icon: "users",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
    marker: "bg-[#2170e4]",
    scopes: ["Transactions", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-2003",
    name: "Interest",
    type: "Income",
    description: "Savings and investment interest",
    monthlyAverage: "$95",
    transactionCount: 3,
    icon: "savings",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
    marker: "bg-[#4f46e5]",
    scopes: ["Transactions", "Accounts", "Savings Goals", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-2004",
    name: "Bonus",
    type: "Income",
    description: "Performance and annual bonus",
    monthlyAverage: "$600",
    transactionCount: 1,
    icon: "target",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
    marker: "bg-[#92400e]",
    scopes: ["Transactions", "Savings Goals", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-2005",
    name: "Other Income",
    type: "Income",
    description: "Refunds and irregular income",
    monthlyAverage: "$210",
    transactionCount: 5,
    icon: "plus",
    tone: "text-[#45464d]",
    bg: "bg-[#f8f9ff]",
    marker: "bg-[#76777d]",
    scopes: ["Transactions", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3001",
    name: "Everyday Banking",
    type: "Income",
    description: "Checking and daily cash flow accounts",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "account",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
    marker: "bg-[#2170e4]",
    scopes: ["Accounts", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3002",
    name: "Credit Accounts",
    type: "Expense",
    description: "Credit cards and revolving liabilities",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "credit",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
    marker: "bg-[#b42318]",
    scopes: ["Accounts", "Debts", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3003",
    name: "Emergency Reserve",
    type: "Income",
    description: "Emergency savings and liquidity goals",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "savings",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
    marker: "bg-[#047857]",
    scopes: ["Savings Goals", "Accounts", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3004",
    name: "Loan Repayment",
    type: "Expense",
    description: "Debt repayment and liability tracking",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "document",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
    marker: "bg-[#4f46e5]",
    scopes: ["Debts", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3005",
    name: "Software Tools",
    type: "Expense",
    description: "Productivity and professional software subscriptions",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "subscriptions",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
    marker: "bg-[#2170e4]",
    scopes: ["Subscriptions", "Transactions", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3006",
    name: "Entertainment",
    type: "Expense",
    description: "Streaming, media, and entertainment services",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "box",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
    marker: "bg-[#4f46e5]",
    scopes: ["Subscriptions", "Transactions", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3007",
    name: "Electronics",
    type: "Expense",
    description: "Phones, laptops, and personal technology",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "credit",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
    marker: "bg-[#2170e4]",
    scopes: ["Assets", "Transactions", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3008",
    name: "Accessories",
    type: "Expense",
    description: "Watches, bags, and personal accessories",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "box",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
    marker: "bg-[#92400e]",
    scopes: ["Assets", "Reports"],
    status: "Active",
  },
  {
    id: "CAT-3009",
    name: "Furniture",
    type: "Expense",
    description: "Home office and household furniture",
    monthlyAverage: "$0",
    transactionCount: 0,
    icon: "home",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
    marker: "bg-[#047857]",
    scopes: ["Assets", "Reports"],
    status: "Active",
  },
];
