import type { SummaryMetric, Transaction, TransactionFilterOptions } from "@/types/finance";

export const transactionSummaries: SummaryMetric[] = [
  {
    label: "Income This Month",
    value: "+MMK 8,450.00",
    icon: "trendingUp",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Expenses This Month",
    value: "-MMK 3,240.50",
    icon: "trendingDown",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    label: "Transfers",
    value: "MMK 1,000.00",
    icon: "sync",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
  {
    label: "Net Balance",
    value: "+MMK 5,209.50",
    icon: "savings",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
];

export const transactions: Transaction[] = [
  {
    id: "TRX-1007",
    date: "Jun 14, 2026",
    type: "Expense",
    category: "Food",
    account: "Chase Sapphire",
    paymentMethod: "Credit Card",
    amount: "-MMK 142.50",
    note: "Whole Foods Market - weekly groceries",
    attachment: "receipt",
  },
  {
    id: "TRX-1006",
    date: "Jun 13, 2026",
    type: "Expense",
    category: "Subscriptions",
    account: "Amex Platinum",
    paymentMethod: "Credit Card",
    amount: "-MMK 20.00",
    note: "ChatGPT monthly subscription",
    linkedBudgetId: "BUD-1006",
    linkedSubscriptionId: "SUB-1001",
  },
  {
    id: "TRX-1005",
    date: "Jun 12, 2026",
    type: "Income",
    category: "Income",
    account: "Main Checking",
    paymentMethod: "Direct Deposit",
    amount: "+MMK 4,250.00",
    note: "Salary deposit - Apex Systems",
    attachment: "document",
  },
  {
    id: "TRX-1004",
    date: "Jun 10, 2026",
    type: "Transfer",
    category: "Transfer",
    account: "High-Yield Savings",
    paymentMethod: "Internal Transfer",
    amount: "MMK 500.00",
    note: "Move funds to emergency savings",
    linkedSavingsGoalId: "SVG-1001",
  },
  {
    id: "TRX-1003",
    date: "Jun 09, 2026",
    type: "Expense",
    category: "Housing",
    account: "Main Checking",
    paymentMethod: "ACH",
    amount: "-MMK 1,850.00",
    note: "Monthly apartment rent",
    attachment: "document",
    linkedBudgetId: "BUD-1001",
    linkedDebtId: "DEBT-1001",
  },
  {
    id: "TRX-1002",
    date: "Jun 08, 2026",
    type: "Expense",
    category: "Utilities",
    account: "Main Checking",
    paymentMethod: "Debit Card",
    amount: "-MMK 96.80",
    note: "Internet and mobile plan",
    linkedBudgetId: "BUD-1005",
  },
  {
    id: "TRX-1001",
    date: "Jun 07, 2026",
    type: "Expense",
    category: "Travel",
    account: "Travel Wallet",
    paymentMethod: "Digital Wallet",
    amount: "-MMK 58.35",
    note: "Airport ride share",
    attachment: "receipt",
    linkedBudgetId: "BUD-1003",
  },
];

export const transactionFilterOptions: TransactionFilterOptions = {
  category: ["Category", "Food", "Housing", "Income", "Subscriptions", "Transfer", "Travel", "Utilities"],
  account: ["Account", "Chase Sapphire", "Amex Platinum", "Main Checking", "High-Yield Savings", "Travel Wallet"],
  type: ["Type", "Income", "Expense", "Transfer"],
  amount: ["Amount", "> MMK 100", "< MMK 100", "MMK 500+"],
};
