import type { DebtRecord, SummaryMetric, UpcomingDebtPayment } from "@/types/finance";

export const debtSummaries: SummaryMetric[] = [
  {
    label: "Total Debt",
    value: "MMK 145,000.00",
    icon: "account",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Total Repaid",
    value: "MMK 42,500.00",
    icon: "trendingUp",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Remaining Debt",
    value: "MMK 102,500.00",
    icon: "chart",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
  {
    label: "Next Payment Due",
    value: "Nov 15, 2026",
    icon: "calendar",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
];

export const debts: DebtRecord[] = [
  {
    id: "DEBT-1001",
    name: "Mortgage",
    lender: "Chase Bank",
    totalAmount: "MMK 350,000.00",
    repaidAmount: "MMK 40,000.00",
    remainingBalance: "MMK 310,000.00",
    monthlyPayment: "MMK 2,100.00",
    interestRate: "5.85%",
    nextPaymentDate: "Nov 15, 2026",
    progressPercent: 11,
    status: "Active",
    icon: "home",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "DEBT-1002",
    name: "Student Loan",
    lender: "Federal Student Aid",
    totalAmount: "MMK 45,000.00",
    repaidAmount: "MMK 2,500.00",
    remainingBalance: "MMK 42,500.00",
    monthlyPayment: "MMK 450.00",
    interestRate: "4.20%",
    nextPaymentDate: "Nov 01, 2026",
    progressPercent: 6,
    status: "Overdue",
    icon: "document",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    id: "DEBT-1003",
    name: "Car Loan",
    lender: "Toyota Financial",
    totalAmount: "MMK 25,000.00",
    repaidAmount: "MMK 25,000.00",
    remainingBalance: "MMK 0.00",
    monthlyPayment: "-",
    interestRate: "3.95%",
    nextPaymentDate: "-",
    progressPercent: 100,
    status: "Paid",
    icon: "credit",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "DEBT-1004",
    name: "Personal Loan",
    lender: "SoFi",
    totalAmount: "MMK 18,000.00",
    repaidAmount: "MMK 8,300.00",
    remainingBalance: "MMK 9,700.00",
    monthlyPayment: "MMK 320.00",
    interestRate: "7.25%",
    nextPaymentDate: "Dec 01, 2026",
    progressPercent: 46,
    status: "Active",
    icon: "account",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
];

export const upcomingDebtPayments: UpcomingDebtPayment[] = [
  {
    id: "PAY-1001",
    debtName: "Student Loan",
    dueLabel: "Overdue (Nov 01)",
    amount: "MMK 450.00",
    isOverdue: true,
  },
  {
    id: "PAY-1002",
    debtName: "Mortgage",
    dueLabel: "Due: Nov 15",
    amount: "MMK 2,100.00",
  },
  {
    id: "PAY-1003",
    debtName: "Personal Loan",
    dueLabel: "Due: Dec 01",
    amount: "MMK 320.00",
  },
];
