import type { AssetRecord, SummaryMetric } from "@/types/finance";

export const assetSummaries: SummaryMetric[] = [
  {
    label: "Total Purchase Value",
    value: "$8,420.00",
    icon: "box",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Current Value",
    value: "$5,960.00",
    icon: "chart",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Active Assets",
    value: "6",
    icon: "dashboard",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Needs Review",
    value: "1",
    icon: "bell",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
];

export const assets: AssetRecord[] = [
  {
    id: "AST-1001",
    name: "MacBook Pro 14",
    category: "Electronics",
    purchaseDate: "Jan 12, 2024",
    startUsingDate: "Jan 15, 2024",
    purchaseAmount: "$2,499.00",
    currentValue: "$1,850.00",
    usageDuration: "2 years 5 months",
    condition: "Excellent",
    status: "Active",
    note: "Primary work laptop",
    icon: "credit",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "AST-1002",
    name: "Omega Seamaster",
    category: "Accessories",
    purchaseDate: "Aug 03, 2022",
    startUsingDate: "Aug 05, 2022",
    purchaseAmount: "$4,200.00",
    currentValue: "$3,500.00",
    usageDuration: "3 years 10 months",
    condition: "Good",
    status: "Active",
    note: "Personal watch",
    icon: "box",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
  {
    id: "AST-1003",
    name: "Standing Desk",
    category: "Furniture",
    purchaseDate: "Mar 18, 2025",
    startUsingDate: "Mar 20, 2025",
    purchaseAmount: "$650.00",
    currentValue: "$420.00",
    usageDuration: "1 year 3 months",
    condition: "Good",
    status: "Active",
    note: "Home office desk",
    icon: "home",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "AST-1004",
    name: "iPhone 15 Pro",
    category: "Electronics",
    purchaseDate: "Sep 23, 2023",
    startUsingDate: "Sep 23, 2023",
    purchaseAmount: "$1,071.00",
    currentValue: "$190.00",
    usageDuration: "2 years 8 months",
    condition: "Needs Repair",
    status: "Active",
    note: "Battery service recommended",
    icon: "credit",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
];
