import type { FinancialAccount, SummaryMetric } from "@/types/finance";

export const accountSummaries: SummaryMetric[] = [
  {
    label: "Total Balance",
    value: "$24,892.65",
    icon: "account",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Cash Available",
    value: "$8,614.30",
    icon: "savings",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Credit Used",
    value: "$2,113.75",
    icon: "credit",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    label: "Active Accounts",
    value: "5",
    icon: "dashboard",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
];

export const accounts: FinancialAccount[] = [
  {
    id: "ACC-1001",
    name: "Main Checking",
    type: "Bank Account",
    institution: "Chase Bank",
    balance: "$6,824.30",
    availableBalance: "$6,824.30",
    accountNumber: "...4582",
    currency: "USD",
    lastUpdated: "Jun 15, 2026",
    monthlyInflow: "+$4,250.00",
    monthlyOutflow: "-$2,014.85",
    transactionCount: 42,
    status: "Active",
    icon: "account",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "ACC-1002",
    name: "High-Yield Savings",
    type: "Savings",
    institution: "Ally Bank",
    balance: "$14,250.00",
    availableBalance: "$14,250.00",
    accountNumber: "...7720",
    currency: "USD",
    lastUpdated: "Jun 15, 2026",
    monthlyInflow: "+$500.00",
    monthlyOutflow: "$0.00",
    transactionCount: 8,
    status: "Active",
    icon: "savings",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "ACC-1003",
    name: "Amex Platinum",
    type: "Credit Card",
    institution: "American Express",
    balance: "-$1,430.20",
    availableBalance: "$8,569.80",
    accountNumber: "...9921",
    currency: "USD",
    lastUpdated: "Jun 14, 2026",
    monthlyInflow: "$0.00",
    monthlyOutflow: "-$1,430.20",
    transactionCount: 16,
    status: "Active",
    icon: "credit",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    id: "ACC-1004",
    name: "Travel Wallet",
    type: "Digital Wallet",
    institution: "Wise",
    balance: "$812.15",
    availableBalance: "$812.15",
    accountNumber: "...1048",
    currency: "USD",
    lastUpdated: "Jun 13, 2026",
    monthlyInflow: "+$300.00",
    monthlyOutflow: "-$58.35",
    transactionCount: 7,
    status: "Active",
    icon: "credit",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
  {
    id: "ACC-1005",
    name: "Cash Wallet",
    type: "Cash Wallet",
    institution: "Personal Cash",
    balance: "$436.40",
    availableBalance: "$436.40",
    accountNumber: "Cash",
    currency: "USD",
    lastUpdated: "Jun 11, 2026",
    monthlyInflow: "+$200.00",
    monthlyOutflow: "-$186.60",
    transactionCount: 13,
    status: "Needs Review",
    icon: "box",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
  {
    id: "ACC-1006",
    name: "Chase Sapphire",
    type: "Credit Card",
    institution: "Chase Bank",
    balance: "-$683.55",
    availableBalance: "$11,316.45",
    accountNumber: "...2288",
    currency: "USD",
    lastUpdated: "Jun 14, 2026",
    monthlyInflow: "$0.00",
    monthlyOutflow: "-$683.55",
    transactionCount: 10,
    status: "Active",
    icon: "credit",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
];
