import type { BudgetCategory, SummaryMetric } from "@/types/finance";

export const budgetSummaries: SummaryMetric[] = [
  {
    label: "Total Budget",
    value: "$5,200.00",
    icon: "savings",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Actual Spending",
    value: "$3,450.00",
    icon: "receipt",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Remaining",
    value: "$1,750.00",
    icon: "trendingUp",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Action Needed",
    value: "2",
    icon: "bell",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
];

export const budgetCategories: BudgetCategory[] = [
  {
    id: "BUD-1001",
    category: "Housing",
    period: "Monthly",
    budget: "$2,100",
    actual: "$2,100",
    remaining: "$0",
    usagePercent: 100,
    status: "Under Budget",
    icon: "home",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "BUD-1002",
    category: "Food",
    period: "Monthly",
    budget: "$800",
    actual: "$850",
    remaining: "-$50",
    usagePercent: 106,
    status: "Over Budget",
    icon: "food",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    id: "BUD-1003",
    category: "Travel",
    period: "Monthly",
    budget: "$500",
    actual: "$120",
    remaining: "$380",
    usagePercent: 24,
    status: "Under Budget",
    icon: "travel",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "BUD-1004",
    category: "Shopping",
    period: "Monthly",
    budget: "$400",
    actual: "$420",
    remaining: "-$20",
    usagePercent: 105,
    status: "Over Budget",
    icon: "shopping",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    id: "BUD-1005",
    category: "Utilities",
    period: "Monthly",
    budget: "$300",
    actual: "$280",
    remaining: "$20",
    usagePercent: 93,
    status: "Near Limit",
    icon: "settings",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
  {
    id: "BUD-1006",
    category: "Subscriptions",
    period: "Monthly",
    budget: "$250",
    actual: "$160",
    remaining: "$90",
    usagePercent: 64,
    status: "Under Budget",
    icon: "subscriptions",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
  {
    id: "BUD-2001",
    category: "Housing",
    period: "Yearly",
    budget: "$25,200",
    actual: "$12,600",
    remaining: "$12,600",
    usagePercent: 50,
    status: "Under Budget",
    icon: "home",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "BUD-2002",
    category: "Food",
    period: "Yearly",
    budget: "$9,600",
    actual: "$5,780",
    remaining: "$3,820",
    usagePercent: 60,
    status: "Under Budget",
    icon: "food",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "BUD-2003",
    category: "Travel",
    period: "Yearly",
    budget: "$6,000",
    actual: "$4,920",
    remaining: "$1,080",
    usagePercent: 82,
    status: "Near Limit",
    icon: "travel",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
];
