import type { BudgetCategory, SummaryMetric } from "@/types/finance";

export const budgetSummaries: SummaryMetric[] = [
  {
    label: "Total Budget",
    value: "MMK 5,200.00",
    icon: "savings",
    tone: "text-[#0b1c30]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Actual Spending",
    value: "MMK 3,450.00",
    icon: "receipt",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    label: "Remaining",
    value: "MMK 1,750.00",
    icon: "trendingUp",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    label: "Action Needed",
    value: "2",
    icon: "bell",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
];

export const budgetCategories: BudgetCategory[] = [
  {
    id: "BUD-1001",
    category: "Housing",
    period: "Monthly",
    budget: "MMK 2,100",
    actual: "MMK 2,100",
    remaining: "MMK 0",
    usagePercent: 100,
    status: "Under Budget",
    icon: "home",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "BUD-1002",
    category: "Food",
    period: "Monthly",
    budget: "MMK 800",
    actual: "MMK 850",
    remaining: "-MMK 50",
    usagePercent: 106,
    status: "Over Budget",
    icon: "food",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    id: "BUD-1003",
    category: "Travel",
    period: "Monthly",
    budget: "MMK 500",
    actual: "MMK 120",
    remaining: "MMK 380",
    usagePercent: 24,
    status: "Under Budget",
    icon: "travel",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "BUD-1004",
    category: "Shopping",
    period: "Monthly",
    budget: "MMK 400",
    actual: "MMK 420",
    remaining: "-MMK 20",
    usagePercent: 105,
    status: "Over Budget",
    icon: "shopping",
    tone: "text-[#b42318]",
    bg: "bg-[#fff1f0]",
  },
  {
    id: "BUD-1005",
    category: "Utilities",
    period: "Monthly",
    budget: "MMK 300",
    actual: "MMK 280",
    remaining: "MMK 20",
    usagePercent: 93,
    status: "Near Limit",
    icon: "settings",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
  {
    id: "BUD-1006",
    category: "Subscriptions",
    period: "Monthly",
    budget: "MMK 250",
    actual: "MMK 160",
    remaining: "MMK 90",
    usagePercent: 64,
    status: "Under Budget",
    icon: "subscriptions",
    tone: "text-[#4f46e5]",
    bg: "bg-[#eef2ff]",
  },
  {
    id: "BUD-2001",
    category: "Housing",
    period: "Yearly",
    budget: "MMK 25,200",
    actual: "MMK 12,600",
    remaining: "MMK 12,600",
    usagePercent: 50,
    status: "Under Budget",
    icon: "home",
    tone: "text-[#0058be]",
    bg: "bg-[#eff6ff]",
  },
  {
    id: "BUD-2002",
    category: "Food",
    period: "Yearly",
    budget: "MMK 9,600",
    actual: "MMK 5,780",
    remaining: "MMK 3,820",
    usagePercent: 60,
    status: "Under Budget",
    icon: "food",
    tone: "text-[#047857]",
    bg: "bg-[#ecfdf5]",
  },
  {
    id: "BUD-2003",
    category: "Travel",
    period: "Yearly",
    budget: "MMK 6,000",
    actual: "MMK 4,920",
    remaining: "MMK 1,080",
    usagePercent: 82,
    status: "Near Limit",
    icon: "travel",
    tone: "text-[#92400e]",
    bg: "bg-[#fffbeb]",
  },
];
